-- Schema dump generated by zdd

-- Table: public.test_users
CREATE TABLE public.test_users (id integer, name character varying, email character varying);

-- Table: zdd_deployments.applied_deployments
CREATE TABLE zdd_deployments.applied_deployments (id character varying, name character varying, applied_at timestamp with time zone, checksum character varying);

-- Index: idx_users_email
CREATE INDEX idx_users_email ON public.test_users USING btree (email);

-- Index: idx_applied_deployments_applied_at
CREATE INDEX idx_applied_deployments_applied_at ON zdd_deployments.applied_deployments USING btree (applied_at);
