-- Schema dump generated by zdd

-- Table: public.test_users
CREATE TABLE public.test_users (id integer, name character varying, email character varying, created_at timestamp with time zone);

-- Table: zdd_migrations.applied_migrations
CREATE TABLE zdd_migrations.applied_migrations (id character varying, name character varying, applied_at timestamp with time zone, checksum character varying);

-- Index: test_users_email_key
CREATE UNIQUE INDEX test_users_email_key ON public.test_users USING btree (email);

-- Index: idx_applied_migrations_applied_at
CREATE INDEX idx_applied_migrations_applied_at ON zdd_migrations.applied_migrations USING btree (applied_at);
